language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t mactto3487/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true mactto3487/react-test-app npm run test

after_success:
  - docker build -t mactto3487/docker-frontend ./frontend
  - docker build -t mactto3487/docker-backend ./backend
  - docker build -t mactto3487/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push mactto3487/docker-frontend
  - docker push mactto3487/docker-backend
  - docker push mactto3487/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-2."
  app: "docker-fullstack-app"
  enf: "Dockerfullstackapp-env"
  bucket_name: elasticbeanstalk-us-east-2-523590378911
  bucket_path: "docker-fullstack-app"
  on:
    branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY